/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-04-24 at 15:02:29 UTC 
 * Modify at your own risk.
 */

package com.appspot.linear_axle_547.requestcontroller;

/**
 * Service definition for Requestcontroller (v1).
 *
 * <p>
 * our endpoint for matching requests
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link RequestcontrollerRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Requestcontroller extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the requestcontroller library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://linear-axle-547.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "requestcontroller/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Requestcontroller(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Requestcontroller(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "findMatch".
   *
   * This request holds the parameters needed by the the requestcontroller server.  After setting any
   * optional parameters, call the {@link FindMatch#execute()} method to invoke the remote operation.
   *
   * @param requestId
   * @return the request
   */
  public FindMatch findMatch(java.lang.Long requestId) throws java.io.IOException {
    FindMatch result = new FindMatch(requestId);
    initialize(result);
    return result;
  }

  public class FindMatch extends RequestcontrollerRequest<com.appspot.linear_axle_547.requestcontroller.model.LunchDate> {

    private static final String REST_PATH = "matchRequest/{requestId}";

    /**
     * Create a request for the method "findMatch".
     *
     * This request holds the parameters needed by the the requestcontroller server.  After setting
     * any optional parameters, call the {@link FindMatch#execute()} method to invoke the remote
     * operation. <p> {@link
     * FindMatch#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param requestId
     * @since 1.13
     */
    protected FindMatch(java.lang.Long requestId) {
      super(Requestcontroller.this, "GET", REST_PATH, null, com.appspot.linear_axle_547.requestcontroller.model.LunchDate.class);
      this.requestId = com.google.api.client.util.Preconditions.checkNotNull(requestId, "Required parameter requestId must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public FindMatch setAlt(java.lang.String alt) {
      return (FindMatch) super.setAlt(alt);
    }

    @Override
    public FindMatch setFields(java.lang.String fields) {
      return (FindMatch) super.setFields(fields);
    }

    @Override
    public FindMatch setKey(java.lang.String key) {
      return (FindMatch) super.setKey(key);
    }

    @Override
    public FindMatch setOauthToken(java.lang.String oauthToken) {
      return (FindMatch) super.setOauthToken(oauthToken);
    }

    @Override
    public FindMatch setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (FindMatch) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public FindMatch setQuotaUser(java.lang.String quotaUser) {
      return (FindMatch) super.setQuotaUser(quotaUser);
    }

    @Override
    public FindMatch setUserIp(java.lang.String userIp) {
      return (FindMatch) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long requestId;

    /**

     */
    public java.lang.Long getRequestId() {
      return requestId;
    }

    public FindMatch setRequestId(java.lang.Long requestId) {
      this.requestId = requestId;
      return this;
    }

    @Override
    public FindMatch set(String parameterName, Object value) {
      return (FindMatch) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listRequests".
   *
   * This request holds the parameters needed by the the requestcontroller server.  After setting any
   * optional parameters, call the {@link ListRequests#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListRequests listRequests() throws java.io.IOException {
    ListRequests result = new ListRequests();
    initialize(result);
    return result;
  }

  public class ListRequests extends RequestcontrollerRequest<com.appspot.linear_axle_547.requestcontroller.model.RequestCollection> {

    private static final String REST_PATH = "request";

    /**
     * Create a request for the method "listRequests".
     *
     * This request holds the parameters needed by the the requestcontroller server.  After setting
     * any optional parameters, call the {@link ListRequests#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListRequests#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListRequests() {
      super(Requestcontroller.this, "GET", REST_PATH, null, com.appspot.linear_axle_547.requestcontroller.model.RequestCollection.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListRequests setAlt(java.lang.String alt) {
      return (ListRequests) super.setAlt(alt);
    }

    @Override
    public ListRequests setFields(java.lang.String fields) {
      return (ListRequests) super.setFields(fields);
    }

    @Override
    public ListRequests setKey(java.lang.String key) {
      return (ListRequests) super.setKey(key);
    }

    @Override
    public ListRequests setOauthToken(java.lang.String oauthToken) {
      return (ListRequests) super.setOauthToken(oauthToken);
    }

    @Override
    public ListRequests setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListRequests) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListRequests setQuotaUser(java.lang.String quotaUser) {
      return (ListRequests) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListRequests setUserIp(java.lang.String userIp) {
      return (ListRequests) super.setUserIp(userIp);
    }

    @Override
    public ListRequests set(String parameterName, Object value) {
      return (ListRequests) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Requestcontroller}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Requestcontroller}. */
    @Override
    public Requestcontroller build() {
      return new Requestcontroller(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link RequestcontrollerRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setRequestcontrollerRequestInitializer(
        RequestcontrollerRequestInitializer requestcontrollerRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(requestcontrollerRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
